<?php
declare(strict_types=1);

// OktiasBakery SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

OktiasBakeryUtility::setRegistrar(function (OktiasBakeryUtility $u): void {
    $u->clean = [OktiasBakeryClean::class, 'call'];
    $u->done = [OktiasBakeryDone::class, 'call'];
    $u->make_error = [OktiasBakeryMakeError::class, 'call'];
    $u->feature_add = [OktiasBakeryFeatureAdd::class, 'call'];
    $u->feature_hook = [OktiasBakeryFeatureHook::class, 'call'];
    $u->feature_init = [OktiasBakeryFeatureInit::class, 'call'];
    $u->fetcher = [OktiasBakeryFetcher::class, 'call'];
    $u->make_fetch_def = [OktiasBakeryMakeFetchDef::class, 'call'];
    $u->make_context = [OktiasBakeryMakeContext::class, 'call'];
    $u->make_options = [OktiasBakeryMakeOptions::class, 'call'];
    $u->make_request = [OktiasBakeryMakeRequest::class, 'call'];
    $u->make_response = [OktiasBakeryMakeResponse::class, 'call'];
    $u->make_result = [OktiasBakeryMakeResult::class, 'call'];
    $u->make_point = [OktiasBakeryMakePoint::class, 'call'];
    $u->make_spec = [OktiasBakeryMakeSpec::class, 'call'];
    $u->make_url = [OktiasBakeryMakeUrl::class, 'call'];
    $u->param = [OktiasBakeryParam::class, 'call'];
    $u->prepare_auth = [OktiasBakeryPrepareAuth::class, 'call'];
    $u->prepare_body = [OktiasBakeryPrepareBody::class, 'call'];
    $u->prepare_headers = [OktiasBakeryPrepareHeaders::class, 'call'];
    $u->prepare_method = [OktiasBakeryPrepareMethod::class, 'call'];
    $u->prepare_params = [OktiasBakeryPrepareParams::class, 'call'];
    $u->prepare_path = [OktiasBakeryPreparePath::class, 'call'];
    $u->prepare_query = [OktiasBakeryPrepareQuery::class, 'call'];
    $u->graphql_body = [OktiasBakeryGraphql::class, 'body'];
    $u->graphql_errors = [OktiasBakeryGraphql::class, 'errors'];
    $u->result_basic = [OktiasBakeryResultBasic::class, 'call'];
    $u->result_body = [OktiasBakeryResultBody::class, 'call'];
    $u->result_headers = [OktiasBakeryResultHeaders::class, 'call'];
    $u->transform_request = [OktiasBakeryTransformRequest::class, 'call'];
    $u->transform_response = [OktiasBakeryTransformResponse::class, 'call'];
});
